PB303Pronia/Models/Slider.cs
using PB303Pronia.Models.Common;

namespace PB303Pronia.Models
{
    public class Slider:BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string DiscountTitle { get; set; }
        public string ImgUrl { get; set; }

    }
}

PB303Pronia/Areas/admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PB303Pronia.Contexts;
using PB303Pronia.Helpers;
using PB303Pronia.Models;
using PB303Pronia.ViewModels.SliderViewModels;

namespace PB303Pronia.Areas.admin.Controllers
{
    [Area("admin")]
    [AutoValidateAntiforgeryToken]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly string FOLDER_PATH = "";
        public SliderController(AppDbContext context,IWebHostEnvironment webHost)
        {
            _context = context;
            _webHostEnvironment = webHost;
            FOLDER_PATH = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "images");
        }

        public async Task< IActionResult> Index()
        {
            var sliders = await _context.Sliders.ToListAsync(); ;
            return View(sliders);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SliderCreateViewModel vm)
        {
            if(!ModelState.IsValid) return View();
            if(!vm.SliderImage.CheckType())
            {
                ModelState.AddModelError("SliderImage", "Please enter valid input");
                return View(vm);
            }
            if(!vm.SliderImage.CheckSize(3))
            {
                ModelState.AddModelError("SliderImage", "Please enter valid input");
                return View(vm);
            }
            string imgPath=await vm.SliderImage.CreateImageAsync(FOLDER_PATH);
            Slider slider = new Slider()
            {
                Description = vm.Description,
                DiscountTitle = vm.DiscountTitle,
                Title = vm.Title,
                ImgUrl = imgPath,
            };
            await _context.Sliders.AddAsync(slider);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task< IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            var slider = await _context.Sliders.FirstOrDefaultAsync( x=>x.Id==id);
            
            if(slider == null)return NotFound();
            SliderUpdateViewModel vm = new SliderUpdateViewModel()
            {
                Description=slider.Description,
                DiscountTitle=slider.DiscountTitle,
                Title=slider.Title,
                Id=slider.Id,
                ImagePath=slider.ImgUrl
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(SliderUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                foreach(var error in ModelState.Values.SelectMany(x => x.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                return View(vm);
            }
            var existSlider= await _context.Sliders.FirstOrDefaultAsync(x=>x.Id==vm.Id);
            if (existSlider == null) return BadRequest();
            if(vm.SliderImage !=null)
            {
                if (!(vm.SliderImage.CheckType()))
                {
                    ModelState.AddModelError("SliderImage", "Please enter valid input");
                    return View(vm);
                }
                if (!(vm.SliderImage.CheckSize(3)))
                {
                    ModelState.AddModelError("SliderImage", "Please enter valid input");
                    return View(vm);
                }
                var newFileName=Guid.NewGuid()+vm.SliderImage.FileName;
                var newPath=Path.Combine(FOLDER_PATH,newFileName);
                using(FileStream fs =new(newPath, FileMode.Create))
                {
                    await vm.SliderImage.CopyToAsync(fs);
                }
                
                var oldPath= Path.Combine(FOLDER_PATH,existSlider.ImgUrl);
                if(System.IO.File.Exists(oldPath)) System.IO.File.Delete(oldPath);
                existSlider.ImgUrl = newFileName;
            }
            existSlider.Description = vm.Description;
            existSlider.DiscountTitle = vm.DiscountTitle;
            existSlider.Title = vm.Title;
            _context.Sliders.Update(existSlider);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var slider=await _context.Sliders.FindAsync(id);
            if (slider == null) return NotFound();
            SliderDeleteViewModel vm = new SliderDeleteViewModel()
            {
                Id = slider.Id,
                Title = slider.Title,
                ImgUrl = slider.ImgUrl
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(SliderDeleteViewModel vm)
        {
            var existingSlider= await _context.Sliders.FindAsync(vm.Id);
            if (existingSlider == null) return NotFound();
            var path = Path.Combine(FOLDER_PATH,existingSlider.ImgUrl);
            if(System.IO.File.Exists(path))System.IO.File.Delete(path);
            _context.Sliders.Remove(existingSlider);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

PB303Pronia/Areas/admin/Views/Slider/Create.cshtml
@model SliderCreateViewModel
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description">
                Create Slider

            </p>
            <form method="post" class="forms-sample" enctype="multipart/form-data">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>

                <div class="form-group">
                    <label for="exampleInputUsername1">Name</label>
                    <input class="form-control" id="input1" asp-for="Title" placeholder="Name">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>



                <div class="form-group">
                    <label for="exampleInputUsername1">Price</label>
                    <input class="form-control" id="input1" asp-for="DiscountTitle" placeholder="Price">
                    <span asp-validation-for="DiscountTitle" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label for="exampleInputUsername1">Rating</label>
                    <input class="form-control" id="input1" asp-for="Description" placeholder="Rating">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>




                <div class="form-group">
                    <label for="exampleInputUsername1">Main image</label>
                    <input class="form-control" id="input1" asp-for="SliderImage" placeholder="Image">
                    <span asp-validation-for="SliderImage" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>
</div>

PB303Pronia/Areas/admin/Views/Slider/Delete.cshtml
@model SliderDeleteViewModel

<img src="~/assets/images/@Model.ImgUrl" width="300px" height="400px" />
<input type="hidden" asp-for="ImgUrl" value="@Model.ImgUrl" />

<h4>@Model.Title</h4>
<form method="post" asp-action="delete" asp-route-id="@Model.Id">
    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
    <a asp-controller="Slider" asp-action="index">Cancel</a>
</form>

PB303Pronia/Areas/admin/Views/Slider/Index.cshtml
@model List<Slider>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Settings</h4>
            <p class="card-description">
                <a asp-action="Create" class="btn btn-success">Create</a>
            </p>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Image
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                DiscountTitle
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model)
                        {
                            <tr>
                                <td class="py-1">
                                    @product.Id
                                </td>
                                <td>
                                    <img src="~/assets/images/@product.ImgUrl" />
                                </td>
                                <td>
                                    @product.Title
                                </td>
                                <td>
                                    @product.DiscountTitle
                                </td>
                                <td>
                                    <a asp-action="Update" asp-route-id="@product.Id" class="btn btn-warning">Update</a>
                                    <a asp-action="Delete" asp-route-id="@product.Id" class="btn btn-danger">Delete</a>
                                </td>

                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

PB303Pronia/Areas/admin/Views/Slider/Update.cshtml
@model SliderUpdateViewModel

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Default form</h4>
                <p class="card-description">
                    Update slider
                </p>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

                    <div class="form-group">
                        <label for="exampleInputUsername1">Title</label>
                        <input class="form-control" id="input1" asp-for="Title" placeholder="Name">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>



                    <div class="form-group">
                        <label for="exampleInputUsername1">DTitle</label>
                        <input class="form-control" id="input1" asp-for="DiscountTitle" placeholder="Price">
                        <span asp-validation-for="DiscountTitle" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label for="exampleInputUsername1">Description</label>
                        <input class="form-control" id="input1" asp-for="Description" placeholder="Rating">
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>




                    <div class="form-group">
                        <img src="~/assets/images/@Model.ImagePath" alt="Alt" />
                        <input type="hidden" asp-for="ImagePath" value="@Model.ImagePath" />
                        <label for="exampleInputUsername1">Slider image</label>
                        <input class="form-control" id="input1" asp-for="SliderImage" placeholder="Image">
                        <span asp-validation-for="SliderImage" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button asp-action="index" class="btn btn-light">Cancel</button>
                </form>
                <div asp-validation-summary="ModelOnly"></div>
            </div>
        </div>
    </div>
</div>